#[ 
   The code is automatically generated by the genBind tool. 
   Author: ying32
   https://github.com/ying32  
]#

##

{{/* WM消息常量定义 */}}
##
const
{{range $el := .Messages}}
  {{if not (isEmpty $el.Name)}}
  {{$el.Name}}* = {{$el.Value}}{{if not (isEmpty $el.Value2)}} + {{$el.Value2}}{{end}}{{if not (isEmpty $el.Comment)}} # {{html $el.Comment}}{{end}}
  {{else}}
##
  # {{html $el.Comment}}
  {{end}}
{{end}}