#[ 
   The code is automatically generated by the genBind tool. 
   Author: ying32
   https://github.com/ying32  
]#
#{.experimental: "codeReordering".}
##
##
import liblcl, types
##
##
##
type
{{$instName := "Instance"}}
{{/* 基类定义 */}}
{{range $el := .BaseObjects}}
##
  {{$el.ClassName}}*{{if isEmpty $el.BaseClassName}} {.inheritable.}{{end}} = ref object{{if not (isEmpty $el.BaseClassName)}} of {{$el.BaseClassName}}{{end}}
  {{if isEmpty $el.BaseClassName}}  {{$instName}}: pointer{{end}}
{{end}}

{{/* 剩下的类定义 */}}
{{range $el := .Objects}}
{{if not (isBaseObj $el.ClassName)}}
##
  {{$el.ClassName}}* = ref object of {{$el.BaseClassName}}
{{end}}
{{end}}

{{/* 定义的一些函数 */}}
#---------------------------------------------------------------
##
proc CheckPtr*(obj: TObject): pointer =
  if obj != nil:
    return obj.{{$instName}}
  else:
    return nil
##
## -------------------- 转换对象定义 ------------------------------------------
##
template defaultPointerAs =
  if obj == nil:
    return nil
  new(result)
  result.Instance = obj

{{/* As<xxx>方法定义 */}}
## {{/*这里添加一个强制转换的*/}}
{{range $el := .Objects}}
proc As{{rmObjectT $el.ClassName}}*(obj: pointer): {{$el.ClassName}} = defaultPointerAs{{end}}
##

##
proc Instance*(this: TObject): pointer =
  if this != nil:
    return this.{{$instName}}
  else:
    return nil
##
##
{{/*模板定义*/}}
{{define "getlastPs"}}{{if .LastIsReturn}}: {{$ps := lastParam .Params}}{{covType $ps.Type}}{{end}}{{end}}

{{/*当父类为TObject或者为空时，设置构造函数*/}}
{{define "getFree"}}{{if or (eq . "TObject") (eq . "")}}, Free{{end}}{{end}}

{{/*如果是重载的函数，输出重载函数名，返之输出实际函数*/}}
{{define "getOverloadName"}}{{if .IsOverload}}{{.OverloadName}}{{else}}{{.RealName}}{{end}}{{end}}

{{/* 开始生成方法 */}}
{{/* 默认的free过程 */}}
template defaultFree(pName) =
  if (this != nil) and (this.Instance != nil):
     pName(this.Instance)
     this.Instance = nil


{{range $el := .Objects}}
##
#------------------------- {{$el.ClassName}} -------------------------
{{$className := $el.ClassName}}
##
{{$classN := rmObjectT $className}}
{{range $mm := $el.Methods}}
{{if eq $mm.RealName "Create"}}

proc Free*(this: {{$className}}){{if isBaseMethod $el.ClassName $mm.RealName}} {{end}} = defaultFree: {{$classN}}_Free
##
proc New{{$classN}}*({{range $idx, $ps := $mm.Params}}{{if gt $idx 0}}, {{end}}{{$ps.Name}}: {{covType2 $ps.Type}}{{end}}): {{$className}} =
   new(result{{template "getFree" $el.BaseClassName}})
   result.{{$instName}} = {{$mm.Name}}({{range $idx, $ps := $mm.Params}}{{if gt $idx 0}}, {{end}}{{if isObject $ps.Type}}CheckPtr({{$ps.Name}}){{else}}{{$ps.Name}}{{end}}{{end}})
{{else if eq $mm.RealName "Free"}}
{{else if $mm.IsStatic}}
##
proc {{$className}}Class*(): TClass = {{$mm.Name}}()
##
{{else}}
{{if not $mm.IsStatic}}
{{/* 累了，不想弄，直接写好的得了 */}}
{{if eq $mm.RealName "TextRect2"}}
##
proc TextRect*(this: TCanvas, Rect: var TRect, Text: string, AOutStr: var string, TextFormat: TTextFormat): int32 =
  var outstr: cstring
  result = Canvas_TextRect2(this.{{$instName}}, Rect, Text, outstr, TextFormat)
  AOutStr = $outstr
{{else if eq $mm.RealName "CreateForm"}}
##
proc CreateForm*[T](this: TApplication, x: var T) =
    new(x)
    x.{{$instName}} = Application_CreateForm(this.{{$instName}}, false)
##
proc CreateForm*(this: TApplication): TForm =
  AsForm(Application_CreateForm(this.{{$instName}}, false))
{{else}}
##
{{$isSetProp := isSetter $mm}}
{{$notProp := not (isProp $mm)}}
proc {{if $isSetProp}}`{{end}}{{getRealName $mm}}{{if $isSetProp}}=`{{end}}*(this: {{$className}}{{range $idx, $ps := $mm.Params}}{{if canOutParam $mm $idx}}{{if gt $idx 0}}, {{$ps.Name}}: {{if $ps.IsVar}}{{if not (eq $ps.Flag "nonPtr")}}var {{end}}{{end}}{{covType2 $ps.Type}}{{end}}{{end}}{{end}}){{if not (isEmpty $mm.Return)}}: {{covType2 $mm.Return}}{{else}}{{template "getlastPs" $mm}}{{end}}{{if $notProp}}{{if isBaseMethod $el.ClassName $mm.RealName}} {{end}}{{else}} {{end}} =
  {{/*这里生成不需要var的变量*/}}
  {{range $ips, $ps := $mm.Params}}
    {{if and ($ps.IsVar) (eq $ps.Flag "nonPtr")}}
  var ps{{$ips}} = {{$ps.Name}}
    {{end}}
  {{end}}
  {{if not (isEmpty $mm.Return)}}return {{if isObject $mm.Return}}As{{rmObjectT $mm.Return}}({{end}}{{if eq $mm.Return "string"}}${{end}}{{end}}{{$mm.Name}}(this.{{$instName}}{{range $idx, $ps := $mm.Params}}{{if canOutParam $mm $idx}}{{if gt $idx 0}}, {{if isObject $ps.Type}}CheckPtr({{$ps.Name}}){{else}}{{if not (eq $ps.Flag "nonPtr")}}{{$ps.Name}}{{else}}ps{{$idx}}{{end}}{{end}}{{end}}{{else}}{{if $mm.LastIsReturn}}, result{{end}}{{end}}{{end}}){{if and (not (isEmpty $mm.Return)) (isObject $mm.Return)}}){{end}}
{{end}}
{{end}}
{{end}}
{{end}}
{{end}}
##
##
#------------ global vars ----------------------
##
var
  Application* = AsApplication(Application_Instance())
  Screen* = AsScreen(Screen_Instance())
  Mouse* = AsMouse(Mouse_Instance())
  Clipboard* = AsClipboard(Clipboard_Instance())
  Printer* = AsPrinter(Printer_Instance())
